version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    groups:
      composer-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - '*'
