<?php

$identity = 'Le service est édité et exploité par Zacharie Dos Santos, entrepreneur individuel, SIREN 104 531 819, SIRET 104 531 819 00019, domicilié 28 rue Ernest Petit, 21000 Dijon, France.';

return [
    'terms' => [
        'meta' => ['title' => 'Conditions générales d’utilisation — DLP Friends', 'description' => 'Règles d’utilisation du service amical DLP Friends.'],
        'title' => 'Conditions générales d’utilisation', 'date_label' => 'Version applicable au', 'date' => '1er septembre 2026', 'toc_label' => 'Sommaire', 'contact_missing' => 'Adresse de contact à configurer', 'footer' => 'DLP Friends est indépendant et non affilié à Disney ou Disneyland Paris.',
        'sections' => [
            ['id' => 'editeur', 'title' => '1. Éditeur et contact', 'paragraphs' => [$identity, 'Contact : :email.'], 'items' => []],
            ['id' => 'objet', 'title' => '2. Objet du service', 'paragraphs' => ['DLP Friends facilite des rencontres strictement amicales entre fans majeurs de Disneyland Paris. Le service est indépendant et n’est ni affilié, ni approuvé, ni exploité par Disney ou Disneyland Paris.'], 'items' => []],
            ['id' => 'acces', 'title' => '3. Accès et majorité', 'paragraphs' => ['L’inscription est réservée aux personnes âgées d’au moins 18 ans. Chaque membre fournit des informations exactes, protège ses identifiants et reste responsable de son compte.'], 'items' => []],
            ['id' => 'conduite', 'title' => '4. Conduite attendue', 'paragraphs' => ['Les échanges restent respectueux, amicaux et licites. Sont interdits le harcèlement, les menaces, la haine, l’usurpation, la fraude, le spam, le contenu sexuel ou illégal et toute atteinte aux droits ou à la sécurité d’autrui.'], 'items' => []],
            ['id' => 'contenus', 'title' => '5. Profils et messages', 'paragraphs' => ['Le membre reste responsable des contenus qu’il publie. Une conversation privée ne s’ouvre qu’après une découverte réciproque. Aucun résultat, rencontre ou disponibilité permanente n’est garanti.'], 'items' => []],
            ['id' => 'moderation', 'title' => '6. Modération', 'paragraphs' => ['En cas de manquement constaté, l’éditeur peut retirer un contenu, limiter, suspendre ou supprimer un compte de façon proportionnée, notamment pour protéger les membres ou respecter la loi. Aucun outil de signalement intégré n’est annoncé à ce stade ; le contact s’effectue à :email.'], 'items' => []],
            ['id' => 'suppression', 'title' => '7. Suppression du compte', 'paragraphs' => ['Le membre peut supprimer son compte depuis ses réglages. Cette action retire immédiatement les données des systèmes actifs, sous réserve de leur rotation temporaire dans les sauvegardes telle que décrite dans la politique de confidentialité.'], 'items' => []],
            ['id' => 'responsabilite', 'title' => '8. Disponibilité et responsabilité', 'paragraphs' => ['Le service peut être interrompu pour maintenance ou incident. L’éditeur ne répond pas des relations entre membres, des services tiers, ni des dommages indirects, sans exclure les garanties imposées par la loi.'], 'items' => []],
            ['id' => 'propriete', 'title' => '9. Propriété intellectuelle', 'paragraphs' => ['La marque, le code et les contenus propres à DLP Friends restent protégés. Chaque membre garantit disposer des droits sur les contenus qu’il transmet. Les marques Disney appartiennent à leurs titulaires.'], 'items' => []],
            ['id' => 'evolution', 'title' => '10. Évolution et droit applicable', 'paragraphs' => ['Ces conditions peuvent évoluer. La version applicable lors d’une inscription est enregistrée. Elles sont régies par le droit français, sans priver un consommateur de ses protections impératives. Toute question peut être adressée à :email.'], 'items' => []],
        ],
    ],
    'privacy' => [
        'meta' => ['title' => 'Politique de confidentialité — DLP Friends', 'description' => 'Données, finalités, durées et droits des membres de DLP Friends.'],
        'title' => 'Politique de confidentialité', 'date_label' => 'Dernière mise à jour :', 'date' => '1er septembre 2026', 'toc_label' => 'Sommaire', 'contact_missing' => 'Adresse de contact à configurer', 'footer' => 'DLP Friends protège uniquement les données nécessaires au service.',
        'sections' => [
            ['id' => 'responsable', 'title' => '1. Responsable du traitement', 'paragraphs' => [$identity, 'Pour toute question ou demande relative aux données : :email.'], 'items' => []],
            ['id' => 'donnees', 'title' => '2. Données et finalités', 'paragraphs' => ['Nous traitons les données de compte et de sécurité (e-mail, date de naissance, mot de passe haché, locale, vérification, passkeys et double authentification), le profil (nom affiché, bio, avatar, fréquence de visite, centres d’intérêt, visibilité), les découvertes, blocages, correspondances, conversations et messages, ainsi que les journaux techniques nécessaires à la sécurité et au fonctionnement.'], 'items' => ['Créer et sécuriser le compte ; vérifier la majorité.', 'Afficher et classer les profils selon les centres d’intérêt communs.', 'Permettre les découvertes réciproques et la messagerie.', 'Prévenir les abus, diagnostiquer les incidents et respecter la loi.']],
            ['id' => 'bases', 'title' => '3. Bases légales', 'paragraphs' => ['L’exécution du contrat fonde le compte, le profil, la découverte et la messagerie. L’intérêt légitime fonde la sécurité, la prévention des abus et l’amélioration technique proportionnée. Une obligation légale peut imposer certaines conservations. Le consentement est utilisé lorsque la loi l’exige.'], 'items' => []],
            ['id' => 'destinataires', 'title' => '4. Destinataires et hébergement', 'paragraphs' => ['Les données sont accessibles aux seules personnes habilitées et aux prestataires nécessaires. Le VPS est hébergé chez IONOS. MySQL, Redis, Reverb et le stockage compatible S3 sont auto-hébergés dans cette infrastructure. Mailpit est réservé au développement local ; le prestataire SMTP de production sera choisi et cette page mise à jour avant activation. Aucun outil publicitaire, paiement, analytique ou connexion OAuth n’est actuellement activé.'], 'items' => []],
            ['id' => 'durees', 'title' => '5. Durées de conservation', 'paragraphs' => ['Les données du compte sont conservées pendant la vie du compte. Sa suppression les retire immédiatement des systèmes actifs. Les sauvegardes quotidiennes chiffrées de MySQL et des fichiers sont conservées :backup_days jours, puis expirent automatiquement. Des données supprimées peuvent donc y subsister jusqu’à cette échéance ; elles sont isolées et ne sont pas restaurées pour un usage courant. Les journaux techniques quotidiens sont conservés selon la configuration opérationnelle, par défaut 14 jours.'], 'items' => []],
            ['id' => 'securite', 'title' => '6. Sécurité et transferts', 'paragraphs' => ['Nous appliquons des contrôles d’accès, le chiffrement des échanges, le hachage des mots de passe et des sauvegardes chiffrées. Aucun transfert hors de l’Espace économique européen n’est prévu ; tout changement sera encadré et documenté.'], 'items' => []],
            ['id' => 'cookies', 'title' => '7. Cookies', 'paragraphs' => ['Seuls les cookies ou stockages strictement nécessaires à la session, la sécurité, la langue et les préférences d’interface sont utilisés. Aucun cookie publicitaire ou analytique n’est activé.'], 'items' => []],
            ['id' => 'droits', 'title' => '8. Vos droits', 'paragraphs' => ['Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition et, lorsque applicable, la portabilité de vos données à :email. Vous pouvez aussi définir des directives après décès et introduire une réclamation auprès de la CNIL sur cnil.fr. Une vérification d’identité proportionnée peut être demandée.'], 'items' => []],
            ['id' => 'evolution', 'title' => '9. Évolution de la politique', 'paragraphs' => ['Cette politique peut évoluer pour refléter le service ou la loi. La date de mise à jour et les liens publics stables permettent d’identifier la version publiée.'], 'items' => []],
        ],
    ],
];
